// SmartQiyos - App Logic (v5 - Cache Buster)
console.log("APP_V5.JS LOADED - LOCALIZATION FIX ACTIVE");

// --- DATA ---
const STORES = [
    // Electronics
    { id: 'texnomart', name: 'Texnomart', logo: 'https://texnomart.uz/favicon.ico', rating: 4.8, rates: { 3: 0, 6: 0, 12: 12, 18: 24, 24: 36 }, category: 'electronics', url: 'https://texnomart.uz', terms: { uz: '12 oygacha 0%', ru: 'до 12 мес 0%', en: 'up to 12 mo 0%' }, docs: { uz: 'Faqat pasport', ru: 'Только паспорт', en: 'Passport only' }, requirements: { passport: true, income: false } },
    { id: 'mediapark', name: 'MediaPark', logo: 'https://mediapark.uz/favicon.ico', rating: 4.5, rates: { 3: 0, 6: 5, 12: 15, 18: 20, 24: 30 }, category: 'kitchen', url: 'https://mediapark.uz', terms: { uz: '24 oygacha bo\'lib to\'lash', ru: 'рассрочка до 24 мес', en: 'installment up to 24 mo' }, docs: { uz: 'Pasport va daromad', ru: 'Паспорт и доход', en: 'Passport and income' }, requirements: { passport: true, income: true } },
    { id: 'idea', name: 'Idea', logo: 'https://idea.uz/favicon.ico', rating: 4.2, rates: { 3: 0, 6: 0, 12: 0, 18: 15, 24: 25 }, category: 'climate', url: 'https://idea.uz', terms: { uz: 'Muddatli to\'lov 0%', ru: 'Рассрочка 0%', en: '0% Installment' }, docs: { uz: 'Faqat pasport', ru: 'Только паспорт', en: 'Passport only' }, requirements: { passport: true, income: false } },
    { id: 'ishonch', name: 'Ishonch', logo: 'https://ishonch.uz/favicon.ico', rating: 4.6, rates: { 3: 0, 6: 8, 12: 18, 18: 26, 24: 34 }, category: 'home', url: 'https://ishonch.uz', terms: { uz: 'Keng assortiment', ru: 'Широкий выбор', en: 'Wide selection' }, docs: { uz: 'Pasport va yashash joyi', ru: 'Паспорт и прописка', en: 'Passport and residency' }, requirements: { passport: true, income: false } },
    { id: 'crediton', name: 'Crediton', logo: 'https://via.placeholder.com/40', rating: 4.1, rates: { 3: 5, 6: 10, 12: 20, 18: 30, 24: 40 }, category: 'electronics', url: 'https://crediton.uz', terms: { uz: 'Tezkor kredit', ru: 'Быстрый кредит', en: 'Quick credit' }, docs: { uz: 'Pasport', ru: 'Паспорт', en: 'Passport' }, requirements: { passport: true, income: false } },
    { id: 'radius', name: 'Radius', logo: 'https://radius.uz/favicon.ico', rating: 4.4, rates: { 3: 0, 6: 0, 12: 15, 18: 25, 24: 35 }, category: 'electronics', url: 'https://radius.uz', terms: { uz: 'Sifatli xizmat', ru: 'Качественный сервис', en: 'Quality service' }, docs: { uz: 'Pasport', ru: 'Паспорт', en: 'Passport' }, requirements: { passport: true, income: false } },
    
    // Marketplace
    { id: 'uzum', name: 'Uzum Market', logo: 'https://uzum.uz/favicon.ico', rating: 4.9, rates: { 3: 0, 6: 0, 12: 16, 18: 24, 24: 32 }, category: 'marketplace', url: 'https://uzum.uz', terms: { uz: 'Tezkor yetkazish', ru: 'Быстрая доставка', en: 'Fast delivery' }, docs: { uz: 'Karta orqali', ru: 'Через карту', en: 'Via card' }, requirements: { passport: true, income: false } },
    { id: 'olcha', name: 'Olcha', logo: 'https://olcha.uz/favicon.ico', rating: 4.7, rates: { 3: 0, 6: 12, 12: 24, 18: 36, 24: 48 }, category: 'marketplace', url: 'https://olcha.uz', terms: { uz: 'Barcha tovarlar', ru: 'Все товары', en: 'All products' }, docs: { uz: 'Pasport', ru: 'Паспорт', en: 'Passport' }, requirements: { passport: true, income: false } },
    { id: 'asaxiy', name: 'Asaxiy', logo: 'https://asaxiy.uz/favicon.ico', rating: 4.8, rates: { 3: 0, 6: 0, 12: 18, 18: 27, 24: 36 }, category: 'marketplace', url: 'https://asaxiy.uz', terms: { uz: 'Kitob va texnika', ru: 'Книги и техника', en: 'Books & Tech' }, docs: { uz: 'Pasport', ru: 'Паспорт', en: 'Passport' }, requirements: { passport: true, income: false } },
    { id: 'zoodmall', name: 'ZoodMall', logo: 'https://via.placeholder.com/40', rating: 4.0, rates: { 3: 8, 6: 16, 12: 32, 18: 48, 24: 56 }, category: 'marketplace', url: 'https://zoodmall.uz', terms: { uz: 'Xalqaro tovarlar', ru: 'Международные товары', en: 'International goods' }, docs: { uz: 'Ilova orqali', ru: 'Через приложение', en: 'Via App' }, requirements: { passport: true, income: false } },

    // Fintech / Nasiya
    { id: 'uzum_nasiya', name: 'Uzum Nasiya', logo: 'https://uzumnasiya.uz/favicon.ico', rating: 4.9, rates: { 3: 0, 6: 10, 12: 25, 18: 38, 24: 50 }, category: 'fintech', url: 'https://uzumnasiya.uz', terms: { uz: 'Halol muddatli to\'lov', ru: 'Рассрочка Халяль', en: 'Halal Installment' }, docs: { uz: 'Faqat karta', ru: 'Только карта', en: 'Card only' }, requirements: { passport: true, income: false } },
    { id: 'solfy', name: 'Solfy', logo: 'https://solfy.com/favicon.ico', rating: 4.5, rates: { 3: 0, 6: 0, 12: 0, 18: 0, 24: 0 }, category: 'fintech', url: 'https://solfy.com', terms: { uz: 'Foizsiz karta', ru: 'Карта без %', en: 'Interest-free card' }, docs: { uz: 'Daromad tasdig\'i', ru: 'Подтверждение дохода', en: 'Income proof' }, requirements: { passport: true, income: true } },
    { id: 'iman', name: 'Iman', logo: 'https://iman.uz/favicon.ico', rating: 4.8, rates: { 3: 0, 6: 12, 12: 24, 18: 36, 24: 48 }, category: 'fintech', url: 'https://iman.uz', terms: { uz: 'Islomiy moliya', ru: 'Исламские финансы', en: 'Islamic Finance' }, docs: { uz: 'Skoring orqali', ru: 'Через скориng', en: 'Via scoring' }, requirements: { passport: true, income: false } },
    { id: 'intend', name: 'Intend', logo: 'https://intend.uz/favicon.ico', rating: 4.2, rates: { 3: 5, 6: 10, 12: 15, 18: 20, 24: 25 }, category: 'fintech', url: 'https://intend.uz', terms: { uz: 'Qulay to\'lov', ru: 'Удобная оплата', en: 'Convenient payment' }, docs: { uz: 'Pasport', ru: 'Паспорт', en: 'Passport' }, requirements: { passport: true, income: false } },
    { id: 'anorbank', name: 'Anorbank', logo: 'https://anorbank.uz/favicon.ico', rating: 4.7, rates: { 3: 0, 6: 14, 12: 28, 18: 42, 24: 56 }, category: 'fintech', url: 'https://anorbank.uz', terms: { uz: 'Kredit kartalari', ru: 'Кредитные карты', en: 'Credit Cards' }, docs: { uz: 'To\'liq hujjat', ru: 'Полный документ', en: 'Full documents' }, requirements: { passport: true, income: true } },

    // Furniture
    { id: 'home24', name: 'Home24', logo: 'https://home24.uz/favicon.ico', rating: 4.5, rates: { 3: 0, 6: 15, 12: 30, 18: 45, 24: 60 }, category: 'furniture', url: 'https://home24.uz', terms: { uz: 'Shinam uy uchun', ru: 'Для уютного дома', en: 'For cozy home' }, docs: { uz: 'Pasport', ru: 'Паспорт', en: 'Passport' }, requirements: { passport: true, income: false } },
    { id: 'aiko', name: 'AIKO', logo: 'https://aiko.uz/favicon.ico', rating: 4.3, rates: { 3: 0, 6: 10, 12: 20, 18: 30, 24: 40 }, category: 'furniture', url: 'https://aiko.uz', terms: { uz: 'Sifatli mebel', ru: 'Качественная мебель', en: 'Quality furniture' }, docs: { uz: 'Pasport', ru: 'Паспорт', en: 'Passport' }, requirements: { passport: true, income: false } }
];

// ... (skipping long lists for brevity in this scratchpad, but keep full code structure) ...
// (I will actually use the content I read from app.js)
